### ISSUE TITLE
Support Nextjs app directory

### ISSUE THREAD

**Issue by god-of-javascript** [RyanClementsHax/tailwindcss-themer#80]
### Describe the bug

In Nextjs 13 with app directory
if we don't have a client component in the app directory used on the current page, this plugin doesn't work

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/distracted-nightingale-3pqhv4?file=%2Ftailwind.config.js%3A39%2C29

### Steps to reproduce

-

### Expected behavior

Work as expected

### How often does this bug happen?

None

### Platform

Browser

### tailwindcss-themer version

latest

**Comment by RyanClementsHax** [comment]
Thanks for opening this! I'll be sure to take a look at it soon

**Comment by RyanClementsHax** [comment]
Thanks for the reproduction repo. It doesn't seem to work when opened. It fails because certain modules aren't installed like `tailwindcss`, `autoprefixer` and `tailwindcss-themer`. After installing the dependencies, it seems the css config was a little off. I included the tailwind directives in the `globals.css` file and made sure the theme names in the plugin's config matched up with the values in the drop down list. Everything works after that.

https://codesandbox.io/p/sandbox/distracted-nightingale-3pqhv4?file=%2Ftailwind.config.js%3A39%2C29

Also [my website](https://github.com/RyanClementsHax/ryanclements.dev) is an example of using this plugin with next.js's app directory if you want a reference implementation.

Let me know if this works for you!
